# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
#
# TODO compliance info
#


default_platform(:ios)

platform :ios do
  desc "Push a new beta build to Testflight"
  lane :build do
    create_keychain (
        name: ENV["FASTLANE_KEYCHAIN_NAME"],
        password: ENV["FASTLANE_KEYCHAIN_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
    )
    package = load_json(json_path: "package.json")
    match (
        type: "appstore", 
        readonly: is_ci, 
        git_private_key: 'id_rsa',
        keychain_name: ENV["FASTLANE_KEYCHAIN_NAME"],
        keychain_password: ENV["FASTLANE_KEYCHAIN_PASSWORD"],
    )
    increment_version_number( version_number: package["version"], xcodeproj: "ios/App/App.xcodeproj")
    increment_build_number(xcodeproj: "ios/App/App.xcodeproj")
    build_app(workspace: "ios/App/App.xcworkspace", scheme: "Condution")
    upload_to_testflight
  end
end
