# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI to AWS
on:
  push:
    branches:
      - "*v[0-9].[0-9].[0-9]"
      - "main"

jobs:
  build_and_deploy:
    environment: s3-access
    runs-on: ubuntu-latest
          
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Ionic
      run: yarn global add @ionic/cli
    - name: Install dependencies
      run: yarn
    - name: Decrypt secret
      run: ./decrypt.sh
      env:
        SECRETS_PASSPHRASE: ${{ secrets.SECRETS_PASSPHRASE }}
    - name: Build app
      run: CI=false yarn ionic:dist
    - name: Upload to S3
      uses: reggionick/s3-deploy@v3
      with:
        # aws bucket name
        bucket: beta.condution.com
        # directory to upload
        folder: build
        # bucket location
        bucket-region: us-east-2
